apiVersion: v1
kind: Service
metadata:
  name: astroshield-backend
  labels:
    app: astroshield
    component: backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: astroshield
    component: backend 