repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: detect-aws-credentials
    - id: detect-private-key
    - id: check-added-large-files
- repo: https://github.com/awslabs/git-secrets
  rev: v1.3.0
  hooks:
    - id: git-secrets
      args: ['--register-aws']
