version: '3.8'

services:
  # Simplified Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile.simple
    ports:
      - "5002:5002"
    volumes:
      - ./app:/app/app
      - ./requirements-simple.txt:/app/requirements.txt
    restart: always
    environment:
      - PORT=5002
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s 