[build]
builder = "nixpacks"

[build.env]
# Use python311Packages.* to ensure correct packages
NIXPACKS_PKGS = "python311 python311Packages.pip python311Packages.uvicorn python311Packages.setuptools python311Packages.wheel"
# Force Nixpacks to use Python 3.11
NIXPACKS_PYTHON_VERSION = "3.11"
# Nixpacks-recognized environment variable for the build command
NIXPACKS_BUILD_CMD = "pip install -r backend/requirements.txt"

[run]
startCommand = "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 4"

[deploy]
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 100
healthcheckInterval = 15
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[deploy.env]
ENVIRONMENT = "production"
PYTHONPATH = "/app/backend"
PYTHONUNBUFFERED = "1" 