[build]
builder = "Nixpacks"

[build.env]
NIXPACKS_PKGS = "python311, python311Packages.pip, python311Packages.uvicorn"

[build.cmd]
buildCommand = "pip install -r backend/requirements.txt"

[run]
startCommand = "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 4"

[deploy]
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure" 