[phases.setup]
nixPkgs = ["python3", "postgresql_16.dev", "gcc"]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install --upgrade pip",
    "pip install -r requirements.txt",
    "pip install 'pydantic[email]'"
]

[start]
cmd = ". /opt/venv/bin/activate && cd /app && uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 4" 