apiVersion: apps/v1
kind: Deployment
metadata:
  name: astroshield-frontend
  labels:
    app: astroshield
    component: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: astroshield
      component: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: astroshield
        component: frontend
    spec:
      containers:
      - name: frontend
        image: your-registry/astroshield-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "https://api.astroshield.com"
        - name: NEXT_PUBLIC_ENVIRONMENT
          value: "production"
        - name: NEXT_PUBLIC_SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: astroshield-secrets
              key: sentry-dsn
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /api/health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20 