apiVersion: v1
kind: ResourceQuota
metadata:
  name: astroshield-quota
spec:
  hard:
    # Compute resources
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    
    # Storage resources
    requests.storage: 100Gi
    persistentvolumeclaims: "10"
    
    # Object count limits
    pods: "30"
    services: "10"
    secrets: "20"
    configmaps: "20"
    
    # Workload limits
    count/deployments.apps: "10"
    count/statefulsets.apps: "5"
    count/jobs.batch: "20"
    count/cronjobs.batch: "10"

---
apiVersion: v1
kind: LimitRange
metadata:
  name: astroshield-limits
spec:
  limits:
  - type: Container
    default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 200m
      memory: 256Mi
    max:
      cpu: "2"
      memory: 4Gi
    min:
      cpu: 100m
      memory: 128Mi
  
  - type: PersistentVolumeClaim
    max:
      storage: 20Gi
    min:
      storage: 1Gi 