apiVersion: apps/v1
kind: Deployment
metadata:
  name: astroshield-api
  labels:
    app: astroshield
    component: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: astroshield
      component: api
  template:
    metadata:
      labels:
        app: astroshield
        component: api
    spec:
      containers:
      - name: api
        image: astroshield/api:latest
        ports:
        - containerPort: 5003
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 5003
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 5003
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: astroshield-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: astroshield-secrets
              key: redis-url 