apiVersion: v1
kind: SecurityContextConstraint
metadata:
  name: astroshield-security-context
spec:
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
  - ALL
  runAsUser:
    type: MustRunAsNonRoot
    ranges:
    - min: 1000
      max: 65535
  seLinux:
    type: MustRunAs
  supplementalGroups:
    type: MustRunAs
    ranges:
    - min: 1000
      max: 65535
  fsGroup:
    type: MustRunAs
    ranges:
    - min: 1000
      max: 65535
  volumes:
  - configMap
  - emptyDir
  - projected
  - secret
  - downwardAPI
  - persistentVolumeClaim
---
# Update backend deployment security context
apiVersion: apps/v1
kind: Deployment
metadata:
  name: astroshield-backend
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: backend
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
---
# Update frontend deployment security context
apiVersion: apps/v1
kind: Deployment
metadata:
  name: astroshield-frontend
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: frontend
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault 