version: '1.0'
services:
  api:
    name: astroshield-api
    port: 5003
    replicas: 2
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
      requests:
        cpu: "500m"
        memory: "512Mi"
  database:
    name: astroshield-db
    type: postgresql
    version: "14"
    port: 5432
  redis:
    name: astroshield-cache
    port: 6379
    version: "7"

environment:
  production:
    domain: api.astroshield.com
    ssl: true
    monitoring:
      enabled: true
      prometheus: true
      grafana: true
  staging:
    domain: staging.astroshield.com
    ssl: true
  development:
    domain: localhost
    ssl: false 